datasets:

  logs:
    consumers:
    - criticality: LOW
      name: Dev_Debug_Tool
      owner: Engineering
      type: app

  # NYC Taxi Data for user testing
  nyc_taxi:
    owner: "data-engineering"
    upstream: []
    consumers:
      - name: Traffic_Analysis_Dashboard
        type: dashboard
        owner: Data Science
        criticality: HIGH
