dataContractSpecification: 3.1.0
id: urn:datacontract:products
info:
  title: Draft Contract for products
  version: 1.0.0
  status: draft
  owner: data-team
strictMode: false
schema:
- name: products
  physicalType: table
  properties:
  - name: product_id
    physicalType: int64
    quality:
    - metric: unique
      mustBe: true
      severity: critical
    required: true
  - name: product_name
    physicalType: string
    quality: []
    required: false
  - name: price
    physicalType: float64
    quality:
    - metric: unique
      mustBe: true
      severity: critical
    required: true
quality:
- metric: freshness
  threshold: 24h
